User.destroy_all
Pet.destroy_all
Favorite.destroy_all
Application.destroy_all

require 'faker'

puts 'Seeding database with all the furry friends..'

user_1 = User.create(id: 1,
                     username: Faker::Internet.username,
                     email: Faker::Internet.free_email)
user_2 = User.create(id: 2,
                     username: Faker::Internet.username,
                     email: Faker::Internet.free_email)
user_3 = User.create(id: 3,
                     username: Faker::Internet.username,
                     email: Faker::Internet.free_email)
user_4 = User.create(id: 4,
                     username: Faker::Internet.username,
                     email: Faker::Internet.free_email)
user_5 = User.create(id: 5,
                     username: Faker::Internet.username,
                     email: Faker::Internet.free_email)
user_6 = User.create(id: 6,
                     username: Faker::Internet.username,
                     email: Faker::Internet.free_email)
user_7 = User.create(id: 7,
                     username: Faker::Internet.username,
                     email: Faker::Internet.free_email)

pet_1 = Pet.create(id: 1,
                   user_id: user_1,
                   name: Faker::Creature::Dog.name,
                   age: [1, 2, 3, 4, 5, 6].sample,
                   pet_type: 1,
                   breed: Faker::Creature::Dog.breed,
                   description: "This is a great dog!",
                   gender: Faker::Creature::Dog.gender,
                   fixed: [true, false].sample,
                   house_trained: [true, false].sample,
                   photo_url_1: "photo_url",
                   photo_url_2: nil,
                   photo_url_3: nil,
                   good_with_kids: [true, false].sample,
                   good_with_animals: [true, false].sample)
pet_2 = Pet.create(id: 2,
                   user_id: user_1,
                   name: Faker::Creature::Dog.name,
                   age: [1, 2, 3, 4, 5, 6].sample,
                   pet_type: 1,
                   breed: Faker::Creature::Dog.breed,
                   description: "This dog is so fluffy",
                   gender: Faker::Creature::Dog.gender,
                   fixed: [true, false].sample,
                   house_trained: [true, false].sample,
                   photo_url_1: "photo_url",
                   photo_url_2: nil,
                   photo_url_3: nil,
                   good_with_kids: [true, false].sample,
                   good_with_animals: [true, false].sample)
pet_3 = Pet.create(id: 3,
                   user_id: user_1,
                   name: Faker::Creature::Cat.name,
                   age: [1, 2, 3, 4, 5, 6].sample,
                   pet_type: 2,
                   breed: Faker::Creature::Cat.breed,
                   description: "This kitty loves to sleep!",
                   gender: 'female',
                   fixed: [true, false].sample,
                   house_trained: [true, false].sample,
                   photo_url_1: "photo_url",
                   photo_url_2: nil,
                   photo_url_3: nil,
                   good_with_kids: [true, false].sample,
                   good_with_animals: [true, false].sample)
pet_4 = Pet.create(id: 4,
                   user_id: user_2,
                   name: Faker::Creature::Cat.name,
                   age: [1, 2, 3, 4, 5, 6].sample,
                   pet_type: 1,
                   breed: Faker::Creature::Cat.breed,
                   description: "They are so snuggly",
                   gender: 'male',
                   fixed: [true, false].sample,
                   house_trained: [true, false].sample,
                   photo_url_1: "photo_url",
                   photo_url_2: nil,
                   photo_url_3: nil,
                   good_with_kids: [true, false].sample,
                   good_with_animals: [true, false].sample)
pet_5 = Pet.create(id: 5,
                   user_id: user_2,
                   name: Faker::Creature::Cat.name,
                   age: [1, 2, 3, 4, 5, 6].sample,
                   pet_type: 1,
                   breed: Faker::Creature::Cat.breed,
                   description: "They are looking for a good home!",
                   gender: 'male',
                   fixed: [true, false].sample,
                   house_trained: [true, false].sample,
                   photo_url_1: "photo_url",
                   photo_url_2: nil,
                   photo_url_3: nil,
                   good_with_kids: [true, false].sample,
                   good_with_animals: [true, false].sample)
pet_6 = Pet.create(id: 6,
                   user_id: user_2,
                   name: Faker::Creature::Dog.name,
                   age: [1, 2, 3, 4, 5, 6].sample,
                   pet_type: 1,
                   breed: Faker::Creature::Dog.breed,
                   description: "They love to play fetch!",
                   gender: Faker::Creature::Dog.gender,
                   fixed: [true, false].sample,
                   house_trained: [true, false].sample,
                   photo_url_1: "photo_url",
                   photo_url_2: nil,
                   photo_url_3: nil,
                   good_with_kids: [true, false].sample,
                   good_with_animals: [true, false].sample)
pet_7 = Pet.create(id: 7,
                   user_id: user_3,
                   name: Faker::Creature::Animal.name,
                   age: [1, 2, 3, 4, 5, 6].sample,
                   pet_type: 0,
                   breed: nil,
                   description: "This snake needs a big terrarium!",
                   gender: 'male',
                   fixed: nil,
                   house_trained: nil,
                   photo_url_1: "photo_url",
                   photo_url_2: nil,
                   photo_url_3: nil,
                   good_with_kids: nil,
                   good_with_animals: nil)
pet_8 = Pet.create(id: 8,
                   user_id: user_3,
                   name: Faker::Creature::Animal.name,
                   age: [1, 2, 3, 4, 5, 6].sample,
                   pet_type: 0,
                   breed: nil,
                   description: "She is a leopard gecko",
                   gender: 'female',
                   fixed: nil,
                   house_trained: nil,
                   photo_url_1: "photo_url",
                   photo_url_2: nil,
                   photo_url_3: nil,
                   good_with_kids: nil,
                   good_with_animals: nil)
pet_9 = Pet.create(id: 9,
                   user_id: user_4,
                   name: Faker::Creature::Dog.name,
                   age: [1, 2, 3, 4, 5, 6].sample,
                   pet_type: 1,
                   breed: Faker::Creature::Dog.breed,
                   description: "This little one needs lots of chew toys!",
                   gender: Faker::Creature::Dog.gender,
                   fixed: [true, false].sample,
                   house_trained: [true, false].sample,
                   photo_url_1: "photo_url",
                   photo_url_2: nil,
                   photo_url_3: nil,
                   good_with_kids: [true, false].sample,
                   good_with_animals: [true, false].sample)
pet_10 = Pet.create(id: 10,
                   user_id: user_4,
                   name: Faker::Creature::Animal.name,
                   age: [1, 2, 3, 4, 5, 6].sample,
                   pet_type: 0,
                   breed: nil,
                   description: "This parakeet loves to sing!",
                   gender: 'female',
                   fixed: nil,
                   house_trained: nil,
                   photo_url_1: "photo_url",
                   photo_url_2: nil,
                   photo_url_3: nil,
                   good_with_kids: nil,
                   good_with_animals: nil)
pet_11 = Pet.create(id: 11,
                   user_id: user_5,
                   name: Faker::Creature::Cat.name,
                   age: [1, 2, 3, 4, 5, 6].sample,
                   pet_type: 1,
                   breed: Faker::Creature::Cat.breed,
                   description: "Loves to catch mice!",
                   gender: 'male',
                   fixed: [true, false].sample,
                   house_trained: [true, false].sample,
                   photo_url_1: "photo_url",
                   photo_url_2: nil,
                   photo_url_3: nil,
                   good_with_kids: [true, false].sample,
                   good_with_animals: [true, false].sample)
pet_12 = Pet.create(id: 12,
                   user_id: user_6,
                   name: Faker::Creature::Dog.name,
                   age: [1, 2, 3, 4, 5, 6].sample,
                   pet_type: 1,
                   breed: Faker::Creature::Dog.breed,
                   description: "Loves to go on walks!",
                   gender: Faker::Creature::Dog.gender,
                   fixed: [true, false].sample,
                   house_trained: [true, false].sample,
                   photo_url_1: "photo_url",
                   photo_url_2: nil,
                   photo_url_3: nil,
                   good_with_kids: [true, false].sample,
                   good_with_animals: [true, false].sample)
puts 'Seeding complete!'
